### ISSUE TITLE
Pre-course Module A: Deployment considerations and recommendations

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-dev-training#10]
Identifies important deployment considerations and presents deployment strategies, including S3 file hosting, based on the business requirements of an Arches application.

**Comment by mradamcox** [comment]
Here are some slides I have used in the past to talk about these topics. The audience was never a super technical one, but I tried to be as technical as would be appropriate. 
[old legion gis deployment-related slides.zip](https://github.com/archesproject/arches-dev-training/files/2416572/old.legion.gis.deployment-related.slides.zip). Also, though it may be a bit out of date, see this document https://www.archesproject.org/implementation-considerations/

Deployment-related questions I have been asked after/while presenting about Arches, and some of the answers I typically give:

- what is the best os to use?
    ...some linux, but first make sure you know what your production environment will be like. (I think a lot of people have wasted time trying to get Arches up and running on windows even though it will be eventually be deployed to a linux server anyway...) Also, if you are installing onto an institution's servers, you may be forced to use something like CentOS. It may make sense in that case to make a staging server on CentOS...
- can multiple arches installations use the same server/postgres/elasticsearch?
    yes, either with multiple domains/subdomains (cleanest) or with subdirectory urls (can get a little tricky). now with v4 mutiple instances can use the same ES, and using the same postgres has always been easy and advisable.
- what is the best cloud provider to use?
    AWS is extremely easy, but some folks are using Azure at this point as well.
- what are arches minimum system requirements?
   ES is the biggest memory user, and needs at least 2gb.... beyond that the app itself can run on a pretty small amount of memory (1gb is plenty), but should have more in production of course...
- with a distributed architecture, what component should be given the most memory for the best performance gains?
- is there an AWS AMI available with dependencies on it already?
    I used to have an up-to-date one, but not at the moment.
- what's the best way to back up an arches database?
    I just have a script that copies pg dump files to S3, and have replication set up on some. RDS can do this for you as well.
- (in the US) does Arches conform to NIST security controls ([800-53](https://nvd.nist.gov/800-53))/are there Arches installations in use by the US federal government?
     no to the latter, and to the former I suspect that some but certainly not all controls are met...

...etc. If I think of more stuff I'll mention it here. General rule of thumb: for any arches question that the farallon team has answered with "that's up to the implementer", then that's something that might be good to cover here (e-mail configuration, e.g.).
